<a href="https://colab.research.google.com/github/sipocz/Colab/blob/main/Segmind_grand_AI_challenge_starter_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Segmind 2021 Grand AI Challenge ##

### Download the dataset ###

In [2]:
!wget https://dockship-public-assets.s3.ap-south-1.amazonaws.com/segmind_grand_ai_challenge_2021-dataset.zip

--2021-05-02 14:30:30--  https://dockship-public-assets.s3.ap-south-1.amazonaws.com/segmind_grand_ai_challenge_2021-dataset.zip
Resolving dockship-public-assets.s3.ap-south-1.amazonaws.com (dockship-public-assets.s3.ap-south-1.amazonaws.com)... 52.219.64.111
Connecting to dockship-public-assets.s3.ap-south-1.amazonaws.com (dockship-public-assets.s3.ap-south-1.amazonaws.com)|52.219.64.111|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6491390 (6.2M) [application/zip]
Saving to: ‘segmind_grand_ai_challenge_2021-dataset.zip’

segmind_grand_ai_ch 100%[===================>]   6.19M  3.22MB/s    in 1.9s

2021-05-02 14:30:33 (3.22 MB/s) - ‘segmind_grand_ai_challenge_2021-dataset.zip’ saved [6491390/6491390]

### Extract the dataset ###

In [3]:
import zipfile
with zipfile.ZipFile("segmind_grand_ai_challenge_2021-dataset.zip", 'r') as zip_ref:
    zip_ref.extractall()

In [4]:
!pip install pandas
!pip install pycaret

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Collecting pycaret
  Downloading https://files.pythonhosted.org/packages/da/99/18f151991b0f06107af9723417c64e304ae2133587f85ea734a90136b4ae/pycaret-2.3.1-py3-none-any.whl (261kB)
     |████████████████████████████████| 266kB 6.3MB/s
Collecting pyLDAvis
  Downloading https://files.pythonhosted.org/packages/03/a5/15a0da6b0150b8b68610cc78af80364a80a9a4c8b6dd5ee549b8989d4b60/pyLDAvis-3.3.1.tar.gz (1.7MB)
     |████████████████████████████████| 1.7MB 7.1MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.17.3)
Collecting pyod
  Downloading https://files.pythonhosted.org/packages/5c/3c/992cf76fd71e5438b2e5400a417ef433e2b1a726570e692102afcacfda33/pyod-0.8.8.tar.gz (102kB)
     |████████████████████████████████| 112kB 41.1MB/s
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.2)
Collecting lightgbm>=2.3.1
  Downloading https://files.pythonhosted.org/packages/18/b2/fff8370f48549ce223f929fe8cab4ee6bf285a41f86037d91312b48ed95b/lightgbm-3.2.1-py3-none-manylinux1_x86_64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 28.5MB/s
Requirement already satisfied: wordcloud in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.5.0)
Requirement already satisfied: numpy==1.19.5 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.19.5)
Collecting scikit-learn==0.23.2
  Downloading https://files.pythonhosted.org/packages/f4/cb/64623369f348e9bfb29ff898a57ac7c91ed4921f228e9726546614d63ccb/scikit_learn-0.23.2-cp37-cp37m-manylinux1_x86_64.whl (6.8MB)
     |████████████████████████████████| 6.8MB 41.9MB/s
Collecting pandas-profiling>=2.8.0
  Downloading https://files.pythonhosted.org/packages/dd/12/e2870750c5320116efe7bebd4ae1709cd7e35e3bc23ac8039864b05b9497/pandas_profiling-2.11.0-py2.py3-none-any.whl (243kB)
     |████████████████████████████████| 245kB 50.6MB/s
Collecting yellowbrick>=1.0.1
  Downloading https://files.pythonhosted.org/packages/3a/15/58feb940b6a2f52d3335cccf9e5d00704ec5ba62782da83f7e2abeca5e4b/yellowbrick-1.3.post1-py3-none-any.whl (271kB)
     |████████████████████████████████| 276kB 49.0MB/s
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.2.5)
Requirement already satisfied: IPython in /usr/local/lib/python3.7/dist-packages (from pycaret) (5.5.0)
Requirement already satisfied: scipy<=1.5.4 in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.4.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.11.1)
Collecting Boruta
  Downloading https://files.pythonhosted.org/packages/b2/11/583f4eac99d802c79af9217e1eff56027742a69e6c866b295cce6a5a8fc2/Boruta-0.3-py3-none-any.whl (56kB)
     |████████████████████████████████| 61kB 6.6MB/s
Collecting mlxtend>=0.17.0
  Downloading https://files.pythonhosted.org/packages/86/30/781c0b962a70848db83339567ecab656638c62f05adb064cb33c0ae49244/mlxtend-0.18.0-py2.py3-none-any.whl (1.3MB)
     |████████████████████████████████| 1.4MB 41.3MB/s
Collecting mlflow
  Downloading https://files.pythonhosted.org/packages/c8/2b/245c8875b2ee51e1a1aa1d27804c87d79a0c770700245575049eac6dcbad/mlflow-1.16.0-py3-none-any.whl (14.2MB)
     |████████████████████████████████| 14.2MB 319kB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.1.5)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.7/dist-packages (from pycaret) (7.6.3)
Collecting scikit-plot
  Downloading https://files.pythonhosted.org/packages/7c/47/32520e259340c140a4ad27c1b97050dd3254fdc517b1d59974d47037510e/scikit_plot-0.3.7-py3-none-any.whl
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pycaret) (1.0.1)
Collecting imbalanced-learn==0.7.0
  Downloading https://files.pythonhosted.org/packages/c8/81/8db4d87b03b998fda7c6f835d807c9ae4e3b141f978597b8d7f31600be15/imbalanced_learn-0.7.0-py3-none-any.whl (167kB)
     |████████████████████████████████| 174kB 41.2MB/s
Collecting kmodes>=0.10.1
  Downloading https://files.pythonhosted.org/packages/9b/34/fffc601aa4d44b94e945a7cc72f477e09dffa7dce888898f2ffd9f4e343e/kmodes-0.11.0-py2.py3-none-any.whl
Collecting umap-learn
  Downloading https://files.pythonhosted.org/packages/75/69/85e7f950bb75792ad5d666d86c5f3e62eedbb942848e7e3126513af9999c/umap-learn-0.5.1.tar.gz (80kB)
     |████████████████████████████████| 81kB 7.0MB/s
Requirement already satisfied: textblob in /usr/local/lib/python3.7/dist-packages (from pycaret) (0.15.3)
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from pycaret) (4.4.1)
Requirement already satisfied: gensim<4.0.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (3.6.0)
Requirement already satisfied: spacy<2.4.0 in /usr/local/lib/python3.7/dist-packages (from pycaret) (2.2.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (56.0.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (0.16.0)
Collecting funcy
  Downloading https://files.pythonhosted.org/packages/66/89/479de0afbbfb98d1c4b887936808764627300208bb771fcd823403645a36/funcy-1.15-py2.py3-none-any.whl
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (0.0)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (2.7.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis->pycaret) (2.11.3)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (0.3.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from cufflinks>=0.17.0->pycaret) (1.15.0)
Requirement already satisfied: numba>=0.35 in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.51.2)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.7/dist-packages (from pyod->pycaret) (0.10.2)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->pycaret) (1.3.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm>=2.3.1->pycaret) (0.36.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/dist-packages (from wordcloud->pycaret) (7.1.2)
Collecting threadpoolctl>=2.0.0
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Collecting tangled-up-in-unicode>=0.0.6
  Downloading https://files.pythonhosted.org/packages/ec/d1/58bfbe263494741a47140049b989ad42a8941854e8d34f1af90640c6c9f9/tangled_up_in_unicode-0.0.7-py3-none-any.whl (3.1MB)
     |████████████████████████████████| 3.2MB 42.4MB/s
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (20.3.0)
Collecting visions[type_image_path]==0.6.0
  Downloading https://files.pythonhosted.org/packages/98/30/b1e70bc55962239c4c3c9660e892be2d8247a882135a3035c10ff7f02cde/visions-0.6.0-py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 5.2MB/s
Collecting htmlmin>=0.1.12
  Downloading https://files.pythonhosted.org/packages/b3/e7/fcd59e12169de19f0131ff2812077f964c6b960e7c09804d30a7bf2ab461/htmlmin-0.1.12.tar.gz
Collecting requests>=2.24.0
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 6.1MB/s
Collecting tqdm>=4.48.2
  Downloading https://files.pythonhosted.org/packages/72/8a/34efae5cf9924328a8f34eeb2fdaae14c011462d9f0e3fcded48e1266d1c/tqdm-4.60.0-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 6.8MB/s
Collecting phik>=0.10.0
  Downloading https://files.pythonhosted.org/packages/b7/ce/193e8ddf62d4be643b9b4b20e8e9c63b2f6a20f92778c0410c629f89bdaa/phik-0.11.2.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 31.6MB/s
Collecting confuse>=1.0.0
  Downloading https://files.pythonhosted.org/packages/6d/55/b4726d81e5d6509fa3441f770f8a9524612627dc1b2a7d6209d1d20083fe/confuse-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.7/dist-packages (from pandas-profiling>=2.8.0->pycaret) (0.4.2)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.8.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (1.0.18)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (0.8.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from IPython->pycaret) (5.0.5)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.4.7)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (7.1.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (3.13)
Collecting prometheus-flask-exporter
  Downloading https://files.pythonhosted.org/packages/4c/d5/8a046d683c2cc084b6a502812827ede69b1064f95d93f94b83f809b21723/prometheus_flask_exporter-0.18.1.tar.gz
Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.4.1)
Collecting querystring-parser
  Downloading https://files.pythonhosted.org/packages/88/6b/572b2590fd55114118bf08bde63c0a421dcc82d593700f3e2ad89908a8a9/querystring_parser-1.2.4-py2.py3-none-any.whl
Collecting alembic<=1.4.1
  Downloading https://files.pythonhosted.org/packages/e0/e9/359dbb77c35c419df0aedeb1d53e71e7e3f438ff64a8fdb048c907404de3/alembic-1.4.1.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 36.8MB/s
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (3.12.4)
Collecting docker>=4.0.0
  Downloading https://files.pythonhosted.org/packages/b2/5a/f988909dfed18c1ac42ad8d9e611e6c5657e270aa6eb68559985dbb69c13/docker-5.0.0-py2.py3-none-any.whl (146kB)
     |████████████████████████████████| 153kB 35.1MB/s
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.3.0)
Collecting gitpython>=2.1.0
  Downloading https://files.pythonhosted.org/packages/a6/99/98019716955ba243657daedd1de8f3a88ca1f5b75057c38e959db22fb87b/GitPython-3.1.14-py3-none-any.whl (159kB)
     |████████████████████████████████| 163kB 45.4MB/s
Collecting databricks-cli>=0.8.7
  Downloading https://files.pythonhosted.org/packages/bc/af/631375abc29e59cedfa4467a5f7755503ba19898890751e1f2636ef02f92/databricks-cli-0.14.3.tar.gz (54kB)
     |████████████████████████████████| 61kB 4.8MB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (2018.9)
Collecting gunicorn; platform_system != "Windows"
  Downloading https://files.pythonhosted.org/packages/e4/dd/5b190393e6066286773a67dfcc2f9492058e9b57c4867a95f1ba5caf0a83/gunicorn-20.1.0-py3-none-any.whl (79kB)
     |████████████████████████████████| 81kB 7.4MB/s
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (0.3)
Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (from mlflow->pycaret) (1.1.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (4.10.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (5.1.3)
Requirement already satisfied: jupyterlab-widgets>=1.0.0; python_version >= "3.6" in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets->pycaret) (3.5.1)
Collecting pynndescent>=0.5
  Downloading https://files.pythonhosted.org/packages/af/65/8189298dd3a05bbad716ee8e249764ff8800e365d8dc652ad2192ca01b4a/pynndescent-0.5.2.tar.gz (1.1MB)
     |████████████████████████████████| 1.2MB 33.4MB/s
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly>=4.4.1->pycaret) (1.3.3)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim<4.0.0->pycaret) (5.0.0)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.8.2)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.0)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.1.3)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.5)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (0.4.1)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (3.0.5)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (1.0.5)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (7.4.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from spacy<2.4.0->pycaret) (2.0.5)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->pyLDAvis->pycaret) (1.1.1)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.7/dist-packages (from numba>=0.35->pyod->pycaret) (0.34.0)
Requirement already satisfied: patsy>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from statsmodels->pyod->pycaret) (0.5.1)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.7/dist-packages (from visions[type_image_path]==0.6.0->pandas-profiling>=2.8.0->pycaret) (2.5.1)
Collecting imagehash; extra == "type_image_path"
  Downloading https://files.pythonhosted.org/packages/8e/18/9dbb772b5ef73a3069c66bb5bf29b9fb4dd57af0d5790c781c3f559bcca6/ImageHash-4.2.0-py2.py3-none-any.whl (295kB)
     |████████████████████████████████| 296kB 37.7MB/s
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.24.0->pandas-profiling>=2.8.0->pycaret) (1.24.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect; sys_platform != "win32"->IPython->pycaret) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython->pycaret) (0.2.5)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/dist-packages (from traitlets>=4.2->IPython->pycaret) (0.2.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->mlflow->pycaret) (3.10.1)
Requirement already satisfied: greenlet!=0.4.17; python_version >= "3" in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->mlflow->pycaret) (1.0.0)
Requirement already satisfied: prometheus_client in /usr/local/lib/python3.7/dist-packages (from prometheus-flask-exporter->mlflow->pycaret) (0.10.1)
Collecting Mako
  Downloading https://files.pythonhosted.org/packages/f3/54/dbc07fbb20865d3b78fdb7cf7fa713e2cba4f87f71100074ef2dc9f9d1f7/Mako-1.1.4-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 6.4MB/s
Collecting python-editor>=0.3
  Downloading https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl
Collecting websocket-client>=0.32.0
  Downloading https://files.pythonhosted.org/packages/08/33/80e0d4f60e84a1ddd9a03f340be1065a2a363c47ce65c4bd3bae65ce9631/websocket_client-0.58.0-py2.py3-none-any.whl (61kB)
     |████████████████████████████████| 61kB 4.9MB/s
Collecting gitdb<5,>=4.0.1
  Downloading https://files.pythonhosted.org/packages/ea/e8/f414d1a4f0bbc668ed441f74f44c116d9816833a48bf81d22b697090dba8/gitdb-4.0.7-py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 6.8MB/s
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.7/dist-packages (from databricks-cli>=0.8.7->mlflow->pycaret) (0.8.9)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask->mlflow->pycaret) (1.0.1)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.1.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.3.5)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (2.6.0)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret) (4.7.1)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret) (5.3.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.7/dist-packages (from imagehash; extra == "type_image_path"->visions[type_image_path]==0.6.0->pandas-profiling>=2.8.0->pycaret) (1.1.1)

In [5]:
import pandas as pd
df=pd.read_csv("./dataset/TRAIN.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.tail(3)

        Store  DayOfWeek        Date  ...  Promo  StateHoliday  SchoolHoliday
712043    344          2  2013-10-01  ...      0             0              1
712044    345          2  2013-10-01  ...      0             0              0
712045    346          2  2013-10-01  ...      0             0              0

[3 rows x 9 columns]

In [7]:
type(df["Date"][0])

str

In [8]:
df=df[df["Open"]==1 ]

In [9]:
a=set(df["StateHoliday"])

In [10]:
print(a)
df["a"]=0
df["b"]=0
df["c"]=0
df["zero"]=0

df["Day1"]=0
df["Day2"]=0
df["Day3"]=0
df["Day4"]=0
df["Day5"]=0
df["Day6"]=0
df["Day7"]=0







df["a"][df["StateHoliday"]=="a"]=1


df["b"][df["StateHoliday"]=="b"]=1

df["c"][df["StateHoliday"]=="c"]=1

df["zero"][df["StateHoliday"]=="0"]=1
df["zero"][df["StateHoliday"]==0]=1


df["Day1"][df["DayOfWeek"]==1]=1
df["Day2"][df["DayOfWeek"]==2]=1
df["Day3"][df["DayOfWeek"]==3]=1
df["Day4"][df["DayOfWeek"]==4]=1
df["Day5"][df["DayOfWeek"]==5]=1
df["Day6"][df["DayOfWeek"]==6]=1
df["Day7"][df["DayOfWeek"]==7]=1

maxi=max(list(df["Sales"]))

df["korr"]=df["Sales"]/maxi


df["Timestamp"]=pd.to_datetime(df["Date"],format="%Y-%m-%d")
df['week_of_year'] = df["Timestamp"].apply(lambda x: x.weekofyear)
df['year'] = df["Timestamp"].apply(lambda x: x.year)

{0, '0', 'c', 'b', 'a'}

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
df.head(26)

    Store  DayOfWeek        Date  ...  Timestamp  week_of_year  year
0       1          5  2015-07-31  ... 2015-07-31            31  2015
1       2          5  2015-07-31  ... 2015-07-31            31  2015
2       3          5  2015-07-31  ... 2015-07-31            31  2015
3       4          5  2015-07-31  ... 2015-07-31            31  2015
4       5          5  2015-07-31  ... 2015-07-31            31  2015
5       6          5  2015-07-31  ... 2015-07-31            31  2015
6       7          5  2015-07-31  ... 2015-07-31            31  2015
7       8          5  2015-07-31  ... 2015-07-31            31  2015
8       9          5  2015-07-31  ... 2015-07-31            31  2015
9      10          5  2015-07-31  ... 2015-07-31            31  2015
10     11          5  2015-07-31  ... 2015-07-31            31  2015
11     12          5  2015-07-31  ... 2015-07-31            31  2015
12     13          5  2015-07-31  ... 2015-07-31            31  2015
13     14          5  2015-07-31  ... 2015-07-31            31  2015
14     15          5  2015-07-31  ... 2015-07-31            31  2015
15     16          5  2015-07-31  ... 2015-07-31            31  2015
16     17          5  2015-07-31  ... 2015-07-31            31  2015
17     18          5  2015-07-31  ... 2015-07-31            31  2015
18     19          5  2015-07-31  ... 2015-07-31            31  2015
19     20          5  2015-07-31  ... 2015-07-31            31  2015
20     21          5  2015-07-31  ... 2015-07-31            31  2015
21     22          5  2015-07-31  ... 2015-07-31            31  2015
22     23          5  2015-07-31  ... 2015-07-31            31  2015
23     24          5  2015-07-31  ... 2015-07-31            31  2015
24     25          5  2015-07-31  ... 2015-07-31            31  2015
25     26          5  2015-07-31  ... 2015-07-31            31  2015

[26 rows x 24 columns]

In [12]:
testdf=pd.read_csv("./dataset/TEST.csv")

In [13]:
testdf[testdf["Store"]==1]

        Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
227         1          1  2013-02-04     1      1            0              0
444         1          3  2013-05-29     1      1            0              0
1191        1          1  2013-07-08     1      0            0              1
1619        1          4  2013-03-28     1      1            0              1
1933        1          4  2013-09-26     1      1            0              0
...       ...        ...         ...   ...    ...          ...            ...
297264      1          7  2013-03-10     0      0            0              0
298023      1          7  2013-01-20     0      0            0              0
299380      1          1  2013-04-15     1      0            0              0
300032      1          1  2013-09-30     1      0            0              0
302953      1          7  2013-04-21     0      0            0              0

[273 rows x 7 columns]

In [14]:
!rm visual_view.py
!wget https://raw.githubusercontent.com/sipocz/messer/main/visual_view.py

rm: cannot remove 'visual_view.py': No such file or directory
--2021-05-02 14:31:31--  https://raw.githubusercontent.com/sipocz/messer/main/visual_view.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1027 (1.0K) [text/plain]
Saving to: ‘visual_view.py’

visual_view.py      100%[===================>]   1.00K  --.-KB/s    in 0s

2021-05-02 14:31:31 (40.2 MB/s) - ‘visual_view.py’ saved [1027/1027]

In [15]:
grafikon=None
from visual_view import grafikon
help(grafikon)

Help on function grafikon in module visual_view:

grafikon(fx, desc1, txt1, desc2='', txt2='', ngraf=2, c1='rgba(35,128,132,0.8)', c2='rgba(193,99,99,0.8)', title=None)
    fx: dataFrame
    desc1:column1
    txt1: label1
    desc2:column2
    txt2: label2
    ngraf: number of graph
    c1: color1
    c2: color2
    title: graph title

In [16]:

from tensorflow.keras.layers import InputLayer, Dense, LSTM, Input, Dropout
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import SGD,Adam,Adamax,Nadam,Ftrl,Adadelta
import tensorflow as tf
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.backend import clear_session
from tensorflow.keras.losses import mean_absolute_percentage_error

In [17]:
df.tail()

        Store  DayOfWeek        Date  ...  Timestamp  week_of_year  year
712041    342          2  2013-10-01  ... 2013-10-01            40  2013
712042    343          2  2013-10-01  ... 2013-10-01            40  2013
712043    344          2  2013-10-01  ... 2013-10-01            40  2013
712044    345          2  2013-10-01  ... 2013-10-01            40  2013
712045    346          2  2013-10-01  ... 2013-10-01            40  2013

[5 rows x 24 columns]

In [18]:
XXX=df[df["Store"]==3 ][:]

In [19]:
XXX.tail()

        Store  DayOfWeek        Date  ...  Timestamp  week_of_year  year
705012      3          1  2013-10-07  ... 2013-10-07            41  2013
707242      3          6  2013-10-05  ... 2013-10-05            40  2013
708357      3          5  2013-10-04  ... 2013-10-04            40  2013
710587      3          3  2013-10-02  ... 2013-10-02            40  2013
711702      3          2  2013-10-01  ... 2013-10-01            40  2013

[5 rows x 24 columns]

In [20]:
XXX["Date_index"]=XXX["Timestamp"]
XXX.index=XXX["Date_index"]

In [21]:
XXX.sort_index(inplace=True)

In [22]:
XXX.reindex()

            Store  DayOfWeek        Date  ...  week_of_year  year  Date_index
Date_index                                ...
2013-10-01      3          2  2013-10-01  ...            40  2013  2013-10-01
2013-10-02      3          3  2013-10-02  ...            40  2013  2013-10-02
2013-10-04      3          5  2013-10-04  ...            40  2013  2013-10-04
2013-10-05      3          6  2013-10-05  ...            40  2013  2013-10-05
2013-10-07      3          1  2013-10-07  ...            41  2013  2013-10-07
...           ...        ...         ...  ...           ...   ...         ...
2015-07-27      3          1  2015-07-27  ...            31  2015  2015-07-27
2015-07-28      3          2  2015-07-28  ...            31  2015  2015-07-28
2015-07-29      3          3  2015-07-29  ...            31  2015  2015-07-29
2015-07-30      3          4  2015-07-30  ...            31  2015  2015-07-30
2015-07-31      3          5  2015-07-31  ...            31  2015  2015-07-31

[552 rows x 25 columns]

In [23]:
prediktorok=["Promo","SchoolHoliday","a","b","c","zero","Day1","Day2","Day3","Day4","Day5","Day6","Day7","korr"]
weeklist=[]
for years in [2013,2014,2015]:
    for weeks in range(1,53):
        #print(years,weeks)
        a=XXX[(XXX["week_of_year"]==weeks) & (XXX["year"]==years)][prediktorok]
        if len(a)==6:
            weeklist.append(a)

In [24]:
weeklist[0]

            Promo  SchoolHoliday  a  b  c  ...  Day4  Day5  Day6  Day7      korr
Date_index                                 ...
2013-10-07      1              0  0  0  0  ...     0     0     0     0  0.259416
2013-10-08      1              0  0  0  0  ...     0     0     0     0  0.223075
2013-10-09      1              0  0  0  0  ...     0     0     0     0  0.198551
2013-10-10      1              0  0  0  0  ...     1     0     0     0  0.209646
2013-10-11      1              0  0  0  0  ...     0     1     0     0  0.170297
2013-10-12      0              0  0  0  0  ...     0     0     1     0  0.098096

[6 rows x 14 columns]

In [57]:
'''
for elem in weeklist:
    if len(elem)==6:
        print(elem)
'''
NN_X=[]
NN_yy=[]

for aweek in weeklist: 
    #print((aweek[prediktorok]).values.tolist())
    #print(len(aweek))
    aaa=((aweek[prediktorok]).values.tolist())
    NN_X.append(aaa)
    suma=0
    for i in range(6):
        suma+=aaa[i][-1]
    
    NN_yy.append(suma)

In [58]:
max_NNy=max(NN_y)

In [60]:
NN_y=[a/max_NNy for a in NN_y]

In [105]:
clear_session()



input_size=13
drop_frac0=0.7  
drop_frac1=0.7  

input1=Input(shape=(6,14))
lstm1=LSTM(116,dropout=0.1,return_sequences=False,)(input1)
l1_out=Dense(9256,activation="sigmoid",)(lstm1) # 
l2_out=Dropout(drop_frac0)(l1_out)


l3_out=Dense(9148,activation="sigmoid",)(l2_out)
l4_out=Dropout(drop_frac1)(l3_out)

pred=Dense(1,activation="sigmoid")(l4_out)

model = Model(inputs=input1, outputs=pred)
optimizer=Adamax(learning_rate=0.000001,) #

model.compile(loss='mae',
    optimizer=optimizer,
    metrics=["mae"])

In [80]:
type(NN_X[1][1][0])

float

In [106]:
 history = model.fit(NN_X[:-1], NN_y[1:], epochs=200, batch_size=32,
                    
                   verbose=1)

Epoch 1/200
3/3 [==============================] - 6s 1s/step - loss: 0.2481 - mae: 0.2481
Epoch 2/200
3/3 [==============================] - 3s 765ms/step - loss: 0.2069 - mae: 0.2069
Epoch 3/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2465 - mae: 0.2465
Epoch 4/200
3/3 [==============================] - 2s 781ms/step - loss: 0.2018 - mae: 0.2018
Epoch 5/200
3/3 [==============================] - 2s 741ms/step - loss: 0.2221 - mae: 0.2221
Epoch 6/200
3/3 [==============================] - 2s 760ms/step - loss: 0.2080 - mae: 0.2080
Epoch 7/200
3/3 [==============================] - 2s 752ms/step - loss: 0.2443 - mae: 0.2443
Epoch 8/200
3/3 [==============================] - 2s 763ms/step - loss: 0.2402 - mae: 0.2402
Epoch 9/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2418 - mae: 0.2418
Epoch 10/200
3/3 [==============================] - 2s 756ms/step - loss: 0.2011 - mae: 0.2011
Epoch 11/200
3/3 [==============================] - 2s 764ms/step - loss: 0.1914 - mae: 0.1914
Epoch 12/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2019 - mae: 0.2019
Epoch 13/200
3/3 [==============================] - 2s 810ms/step - loss: 0.2103 - mae: 0.2103
Epoch 14/200
3/3 [==============================] - 2s 758ms/step - loss: 0.2179 - mae: 0.2179
Epoch 15/200
3/3 [==============================] - 2s 726ms/step - loss: 0.2165 - mae: 0.2165
Epoch 16/200
3/3 [==============================] - 2s 714ms/step - loss: 0.2099 - mae: 0.2099
Epoch 17/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2064 - mae: 0.2064
Epoch 18/200
3/3 [==============================] - 2s 747ms/step - loss: 0.2076 - mae: 0.2076
Epoch 19/200
3/3 [==============================] - 2s 762ms/step - loss: 0.2202 - mae: 0.2202
Epoch 20/200
3/3 [==============================] - 2s 741ms/step - loss: 0.2035 - mae: 0.2035
Epoch 21/200
3/3 [==============================] - 2s 737ms/step - loss: 0.2161 - mae: 0.2161
Epoch 22/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2108 - mae: 0.2108
Epoch 23/200
3/3 [==============================] - 2s 732ms/step - loss: 0.2306 - mae: 0.2306
Epoch 24/200
3/3 [==============================] - 2s 720ms/step - loss: 0.2134 - mae: 0.2134
Epoch 25/200
3/3 [==============================] - 2s 736ms/step - loss: 0.2182 - mae: 0.2182
Epoch 26/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2273 - mae: 0.2273
Epoch 27/200
3/3 [==============================] - 2s 724ms/step - loss: 0.1924 - mae: 0.1924
Epoch 28/200
3/3 [==============================] - 2s 712ms/step - loss: 0.2131 - mae: 0.2131
Epoch 29/200
3/3 [==============================] - 2s 755ms/step - loss: 0.2306 - mae: 0.2306
Epoch 30/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2298 - mae: 0.2298
Epoch 31/200
3/3 [==============================] - 2s 738ms/step - loss: 0.2083 - mae: 0.2083
Epoch 32/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2056 - mae: 0.2056
Epoch 33/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2123 - mae: 0.2123
Epoch 34/200
3/3 [==============================] - 2s 735ms/step - loss: 0.2002 - mae: 0.2002
Epoch 35/200
3/3 [==============================] - 2s 747ms/step - loss: 0.2237 - mae: 0.2237
Epoch 36/200
3/3 [==============================] - 2s 739ms/step - loss: 0.2255 - mae: 0.2255
Epoch 37/200
3/3 [==============================] - 2s 743ms/step - loss: 0.1772 - mae: 0.1772
Epoch 38/200
3/3 [==============================] - 2s 764ms/step - loss: 0.2104 - mae: 0.2104
Epoch 39/200
3/3 [==============================] - 2s 798ms/step - loss: 0.2110 - mae: 0.2110
Epoch 40/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2219 - mae: 0.2219
Epoch 41/200
3/3 [==============================] - 2s 731ms/step - loss: 0.2172 - mae: 0.2172
Epoch 42/200
3/3 [==============================] - 2s 743ms/step - loss: 0.2229 - mae: 0.2229
Epoch 43/200
3/3 [==============================] - 2s 765ms/step - loss: 0.1817 - mae: 0.1817
Epoch 44/200
3/3 [==============================] - 2s 783ms/step - loss: 0.2296 - mae: 0.2296
Epoch 45/200
3/3 [==============================] - 2s 787ms/step - loss: 0.2111 - mae: 0.2111
Epoch 46/200
3/3 [==============================] - 2s 773ms/step - loss: 0.2098 - mae: 0.2098
Epoch 47/200
3/3 [==============================] - 2s 738ms/step - loss: 0.2798 - mae: 0.2798
Epoch 48/200
3/3 [==============================] - 2s 743ms/step - loss: 0.2224 - mae: 0.2224
Epoch 49/200
3/3 [==============================] - 2s 735ms/step - loss: 0.2153 - mae: 0.2153
Epoch 50/200
3/3 [==============================] - 2s 752ms/step - loss: 0.1991 - mae: 0.1991
Epoch 51/200
3/3 [==============================] - 2s 789ms/step - loss: 0.1982 - mae: 0.1982
Epoch 52/200
3/3 [==============================] - 2s 772ms/step - loss: 0.2033 - mae: 0.2033
Epoch 53/200
3/3 [==============================] - 2s 758ms/step - loss: 0.1979 - mae: 0.1979
Epoch 54/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2318 - mae: 0.2318
Epoch 55/200
3/3 [==============================] - 2s 762ms/step - loss: 0.1930 - mae: 0.1930
Epoch 56/200
3/3 [==============================] - 2s 755ms/step - loss: 0.2284 - mae: 0.2284
Epoch 57/200
3/3 [==============================] - 2s 762ms/step - loss: 0.1930 - mae: 0.1930
Epoch 58/200
3/3 [==============================] - 2s 743ms/step - loss: 0.1984 - mae: 0.1984
Epoch 59/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2373 - mae: 0.2373
Epoch 60/200
3/3 [==============================] - 2s 754ms/step - loss: 0.2412 - mae: 0.2412
Epoch 61/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2254 - mae: 0.2254
Epoch 62/200
3/3 [==============================] - 2s 765ms/step - loss: 0.2169 - mae: 0.2169
Epoch 63/200
3/3 [==============================] - 2s 794ms/step - loss: 0.2209 - mae: 0.2209
Epoch 64/200
3/3 [==============================] - 2s 804ms/step - loss: 0.2081 - mae: 0.2081
Epoch 65/200
3/3 [==============================] - 2s 782ms/step - loss: 0.2091 - mae: 0.2091
Epoch 66/200
3/3 [==============================] - 2s 758ms/step - loss: 0.1986 - mae: 0.1986
Epoch 67/200
3/3 [==============================] - 2s 738ms/step - loss: 0.2229 - mae: 0.2229
Epoch 68/200
3/3 [==============================] - 2s 749ms/step - loss: 0.1998 - mae: 0.1998
Epoch 69/200
3/3 [==============================] - 2s 778ms/step - loss: 0.2121 - mae: 0.2121
Epoch 70/200
3/3 [==============================] - 2s 786ms/step - loss: 0.2051 - mae: 0.2051
Epoch 71/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2242 - mae: 0.2242
Epoch 72/200
3/3 [==============================] - 2s 754ms/step - loss: 0.2183 - mae: 0.2183
Epoch 73/200
3/3 [==============================] - 2s 764ms/step - loss: 0.2331 - mae: 0.2331
Epoch 74/200
3/3 [==============================] - 2s 780ms/step - loss: 0.2241 - mae: 0.2241
Epoch 75/200
3/3 [==============================] - 2s 786ms/step - loss: 0.2160 - mae: 0.2160
Epoch 76/200
3/3 [==============================] - 2s 805ms/step - loss: 0.2211 - mae: 0.2211
Epoch 77/200
3/3 [==============================] - 3s 825ms/step - loss: 0.2121 - mae: 0.2121
Epoch 78/200
3/3 [==============================] - 3s 797ms/step - loss: 0.2191 - mae: 0.2191
Epoch 79/200
3/3 [==============================] - 2s 807ms/step - loss: 0.2052 - mae: 0.2052
Epoch 80/200
3/3 [==============================] - 2s 753ms/step - loss: 0.2248 - mae: 0.2248
Epoch 81/200
3/3 [==============================] - 2s 786ms/step - loss: 0.2269 - mae: 0.2269
Epoch 82/200
3/3 [==============================] - 2s 805ms/step - loss: 0.1959 - mae: 0.1959
Epoch 83/200
3/3 [==============================] - 3s 802ms/step - loss: 0.2247 - mae: 0.2247
Epoch 84/200
3/3 [==============================] - 2s 769ms/step - loss: 0.2070 - mae: 0.2070
Epoch 85/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2225 - mae: 0.2225
Epoch 86/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2124 - mae: 0.2124
Epoch 87/200
3/3 [==============================] - 2s 778ms/step - loss: 0.2256 - mae: 0.2256
Epoch 88/200
3/3 [==============================] - 2s 773ms/step - loss: 0.2024 - mae: 0.2024
Epoch 89/200
3/3 [==============================] - 2s 795ms/step - loss: 0.2193 - mae: 0.2193
Epoch 90/200
3/3 [==============================] - 2s 763ms/step - loss: 0.2179 - mae: 0.2179
Epoch 91/200
3/3 [==============================] - 4s 1s/step - loss: 0.2098 - mae: 0.2098
Epoch 92/200
3/3 [==============================] - 2s 735ms/step - loss: 0.2211 - mae: 0.2211
Epoch 93/200
3/3 [==============================] - 2s 760ms/step - loss: 0.1795 - mae: 0.1795
Epoch 94/200
3/3 [==============================] - 2s 786ms/step - loss: 0.2027 - mae: 0.2027
Epoch 95/200
3/3 [==============================] - 2s 740ms/step - loss: 0.2094 - mae: 0.2094
Epoch 96/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2012 - mae: 0.2012
Epoch 97/200
3/3 [==============================] - 2s 764ms/step - loss: 0.1943 - mae: 0.1943
Epoch 98/200
3/3 [==============================] - 2s 736ms/step - loss: 0.2126 - mae: 0.2126
Epoch 99/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2393 - mae: 0.2393
Epoch 100/200
3/3 [==============================] - 2s 752ms/step - loss: 0.2172 - mae: 0.2172
Epoch 101/200
3/3 [==============================] - 2s 753ms/step - loss: 0.2142 - mae: 0.2142
Epoch 102/200
3/3 [==============================] - 2s 742ms/step - loss: 0.2072 - mae: 0.2072
Epoch 103/200
3/3 [==============================] - 2s 734ms/step - loss: 0.2063 - mae: 0.2063
Epoch 104/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2040 - mae: 0.2040
Epoch 105/200
3/3 [==============================] - 2s 731ms/step - loss: 0.2055 - mae: 0.2055
Epoch 106/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2286 - mae: 0.2286
Epoch 107/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2105 - mae: 0.2105
Epoch 108/200
3/3 [==============================] - 2s 739ms/step - loss: 0.2068 - mae: 0.2068
Epoch 109/200
3/3 [==============================] - 2s 747ms/step - loss: 0.2364 - mae: 0.2364
Epoch 110/200
3/3 [==============================] - 2s 741ms/step - loss: 0.1964 - mae: 0.1964
Epoch 111/200
3/3 [==============================] - 2s 738ms/step - loss: 0.2213 - mae: 0.2213
Epoch 112/200
3/3 [==============================] - 2s 741ms/step - loss: 0.1833 - mae: 0.1833
Epoch 113/200
3/3 [==============================] - 2s 763ms/step - loss: 0.2163 - mae: 0.2163
Epoch 114/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2427 - mae: 0.2427
Epoch 115/200
3/3 [==============================] - 2s 758ms/step - loss: 0.1991 - mae: 0.1991
Epoch 116/200
3/3 [==============================] - 2s 761ms/step - loss: 0.1997 - mae: 0.1997
Epoch 117/200
3/3 [==============================] - 2s 742ms/step - loss: 0.2506 - mae: 0.2506
Epoch 118/200
3/3 [==============================] - 2s 735ms/step - loss: 0.2222 - mae: 0.2222
Epoch 119/200
3/3 [==============================] - 2s 776ms/step - loss: 0.2050 - mae: 0.2050
Epoch 120/200
3/3 [==============================] - 2s 784ms/step - loss: 0.1833 - mae: 0.1833
Epoch 121/200
3/3 [==============================] - 2s 762ms/step - loss: 0.2391 - mae: 0.2391
Epoch 122/200
3/3 [==============================] - 2s 738ms/step - loss: 0.2098 - mae: 0.2098
Epoch 123/200
3/3 [==============================] - 2s 766ms/step - loss: 0.1985 - mae: 0.1985
Epoch 124/200
3/3 [==============================] - 2s 768ms/step - loss: 0.2223 - mae: 0.2223
Epoch 125/200
3/3 [==============================] - 2s 784ms/step - loss: 0.2064 - mae: 0.2064
Epoch 126/200
3/3 [==============================] - 2s 802ms/step - loss: 0.2307 - mae: 0.2307
Epoch 127/200
3/3 [==============================] - 2s 763ms/step - loss: 0.2185 - mae: 0.2185
Epoch 128/200
3/3 [==============================] - 2s 743ms/step - loss: 0.1939 - mae: 0.1939
Epoch 129/200
3/3 [==============================] - 2s 759ms/step - loss: 0.1830 - mae: 0.1830
Epoch 130/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2106 - mae: 0.2106
Epoch 131/200
3/3 [==============================] - 2s 754ms/step - loss: 0.2274 - mae: 0.2274
Epoch 132/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2317 - mae: 0.2317
Epoch 133/200
3/3 [==============================] - 2s 741ms/step - loss: 0.1988 - mae: 0.1988
Epoch 134/200
3/3 [==============================] - 2s 768ms/step - loss: 0.2054 - mae: 0.2054
Epoch 135/200
3/3 [==============================] - 2s 734ms/step - loss: 0.2016 - mae: 0.2016
Epoch 136/200
3/3 [==============================] - 2s 728ms/step - loss: 0.2438 - mae: 0.2438
Epoch 137/200
3/3 [==============================] - 2s 751ms/step - loss: 0.1889 - mae: 0.1889
Epoch 138/200
3/3 [==============================] - 3s 812ms/step - loss: 0.2106 - mae: 0.2106
Epoch 139/200
3/3 [==============================] - 3s 798ms/step - loss: 0.1939 - mae: 0.1939
Epoch 140/200
3/3 [==============================] - 2s 765ms/step - loss: 0.2103 - mae: 0.2103
Epoch 141/200
3/3 [==============================] - 2s 741ms/step - loss: 0.2147 - mae: 0.2147
Epoch 142/200
3/3 [==============================] - 2s 733ms/step - loss: 0.1972 - mae: 0.1972
Epoch 143/200
3/3 [==============================] - 2s 741ms/step - loss: 0.1913 - mae: 0.1913
Epoch 144/200
3/3 [==============================] - 2s 775ms/step - loss: 0.2042 - mae: 0.2042
Epoch 145/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2196 - mae: 0.2196
Epoch 146/200
3/3 [==============================] - 2s 767ms/step - loss: 0.2409 - mae: 0.2409
Epoch 147/200
3/3 [==============================] - 2s 754ms/step - loss: 0.2081 - mae: 0.2081
Epoch 148/200
3/3 [==============================] - 2s 728ms/step - loss: 0.1881 - mae: 0.1881
Epoch 149/200
3/3 [==============================] - 2s 757ms/step - loss: 0.2115 - mae: 0.2115
Epoch 150/200
3/3 [==============================] - 2s 775ms/step - loss: 0.2038 - mae: 0.2038
Epoch 151/200
3/3 [==============================] - 2s 773ms/step - loss: 0.2258 - mae: 0.2258
Epoch 152/200
3/3 [==============================] - 2s 758ms/step - loss: 0.1893 - mae: 0.1893
Epoch 153/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2780 - mae: 0.2780
Epoch 154/200
3/3 [==============================] - 2s 757ms/step - loss: 0.1748 - mae: 0.1748
Epoch 155/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2327 - mae: 0.2327
Epoch 156/200
3/3 [==============================] - 2s 750ms/step - loss: 0.2235 - mae: 0.2235
Epoch 157/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2226 - mae: 0.2226
Epoch 158/200
3/3 [==============================] - 2s 733ms/step - loss: 0.2159 - mae: 0.2159
Epoch 159/200
3/3 [==============================] - 2s 761ms/step - loss: 0.2437 - mae: 0.2437
Epoch 160/200
3/3 [==============================] - 2s 730ms/step - loss: 0.2289 - mae: 0.2289
Epoch 161/200
3/3 [==============================] - 2s 732ms/step - loss: 0.2336 - mae: 0.2336
Epoch 162/200
3/3 [==============================] - 2s 733ms/step - loss: 0.2096 - mae: 0.2096
Epoch 163/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2051 - mae: 0.2051
Epoch 164/200
3/3 [==============================] - 2s 767ms/step - loss: 0.2012 - mae: 0.2012
Epoch 165/200
3/3 [==============================] - 2s 765ms/step - loss: 0.2360 - mae: 0.2360
Epoch 166/200
3/3 [==============================] - 2s 730ms/step - loss: 0.2431 - mae: 0.2431
Epoch 167/200
3/3 [==============================] - 2s 721ms/step - loss: 0.2324 - mae: 0.2324
Epoch 168/200
3/3 [==============================] - 2s 741ms/step - loss: 0.1995 - mae: 0.1995
Epoch 169/200
3/3 [==============================] - 2s 742ms/step - loss: 0.2080 - mae: 0.2080
Epoch 170/200
3/3 [==============================] - 2s 748ms/step - loss: 0.1857 - mae: 0.1857
Epoch 171/200
3/3 [==============================] - 2s 727ms/step - loss: 0.1944 - mae: 0.1944
Epoch 172/200
3/3 [==============================] - 2s 744ms/step - loss: 0.2430 - mae: 0.2430
Epoch 173/200
3/3 [==============================] - 2s 724ms/step - loss: 0.2162 - mae: 0.2162
Epoch 174/200
3/3 [==============================] - 2s 727ms/step - loss: 0.2344 - mae: 0.2344
Epoch 175/200
3/3 [==============================] - 2s 735ms/step - loss: 0.1964 - mae: 0.1964
Epoch 176/200
3/3 [==============================] - 2s 752ms/step - loss: 0.2252 - mae: 0.2252
Epoch 177/200
3/3 [==============================] - 2s 811ms/step - loss: 0.2466 - mae: 0.2466
Epoch 178/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2264 - mae: 0.2264
Epoch 179/200
3/3 [==============================] - 2s 744ms/step - loss: 0.2036 - mae: 0.2036
Epoch 180/200
3/3 [==============================] - 2s 753ms/step - loss: 0.1975 - mae: 0.1975
Epoch 181/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2336 - mae: 0.2336
Epoch 182/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2450 - mae: 0.2450
Epoch 183/200
3/3 [==============================] - 2s 772ms/step - loss: 0.2591 - mae: 0.2591
Epoch 184/200
3/3 [==============================] - 2s 755ms/step - loss: 0.2005 - mae: 0.2005
Epoch 185/200
3/3 [==============================] - 2s 749ms/step - loss: 0.2423 - mae: 0.2423
Epoch 186/200
3/3 [==============================] - 2s 733ms/step - loss: 0.2158 - mae: 0.2158
Epoch 187/200
3/3 [==============================] - 2s 733ms/step - loss: 0.1914 - mae: 0.1914
Epoch 188/200
3/3 [==============================] - 2s 751ms/step - loss: 0.2221 - mae: 0.2221
Epoch 189/200
3/3 [==============================] - 3s 886ms/step - loss: 0.2192 - mae: 0.2192
Epoch 190/200
3/3 [==============================] - 3s 846ms/step - loss: 0.2462 - mae: 0.2462
Epoch 191/200
3/3 [==============================] - 4s 974ms/step - loss: 0.2068 - mae: 0.2068
Epoch 192/200
3/3 [==============================] - 3s 1s/step - loss: 0.2337 - mae: 0.2337
Epoch 193/200
3/3 [==============================] - 2s 748ms/step - loss: 0.2181 - mae: 0.2181
Epoch 194/200
3/3 [==============================] - 2s 762ms/step - loss: 0.1980 - mae: 0.1980
Epoch 195/200
3/3 [==============================] - 2s 740ms/step - loss: 0.1963 - mae: 0.1963
Epoch 196/200
3/3 [==============================] - 2s 762ms/step - loss: 0.2108 - mae: 0.2108
Epoch 197/200
3/3 [==============================] - 2s 759ms/step - loss: 0.2204 - mae: 0.2204
Epoch 198/200
3/3 [==============================] - 2s 737ms/step - loss: 0.2113 - mae: 0.2113
Epoch 199/200
3/3 [==============================] - 2s 746ms/step - loss: 0.2126 - mae: 0.2126
Epoch 200/200
3/3 [==============================] - 2s 766ms/step - loss: 0.2254 - mae: 0.2254

In [89]:
datag=pd.DataFrame()
y_pred=model.predict(NN_X[:-1])

In [90]:
y_pred.T

array([[0.53369945, 0.5721004 , 0.52789354, 0.5337119 , 0.57211435,
        0.5337281 , 0.57204336, 0.5336007 , 0.57200974, 0.53334033,
        0.56739515, 0.53075194, 0.5721233 , 0.5337056 , 0.5721075 ,
        0.5336752 , 0.57211244, 0.5337529 , 0.572117  , 0.53367823,
        0.57212067, 0.5337508 , 0.5721164 , 0.5337188 , 0.5721093 ,
        0.53372663, 0.57212234, 0.533806  , 0.5336904 , 0.5720954 ,
        0.5336053 , 0.5664406 , 0.52787244, 0.5664717 , 0.5278582 ,
        0.5278833 , 0.5664652 , 0.53088343, 0.5720954 , 0.53372556,
        0.5720968 , 0.5337403 , 0.5721557 , 0.5278545 , 0.5665027 ,
        0.53384167, 0.53366935, 0.5337613 , 0.5720941 , 0.5336909 ,
        0.5336163 , 0.5720633 , 0.5334386 , 0.53086466, 0.53380054,
        0.5721344 , 0.5338058 , 0.53372765, 0.5721038 , 0.53377146,
        0.57211584, 0.5337152 , 0.5721061 , 0.5337771 , 0.5721041 ,
        0.53371465, 0.57209873, 0.533692  , 0.5337296 , 0.57204056,
        0.5336918 , 0.57206523, 0.527743  , 0.566409  , 0.527849  ]],
      dtype=float32)

In [91]:
datag["pred"]=list(y_pred.T[0])
datag["y"]=list(NN_y[1:])

In [92]:
datag.head()

       pred         y
0  0.533699  0.434859
1  0.572100  0.581378
2  0.527894  0.655215
3  0.533712  0.424927
4  0.572114  0.640049

In [93]:
grafikon(datag,"pred","pred","y","y")