<a href="https://colab.research.google.com/github/sipocz/Colab/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from sklearn.datasets import load_wine
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


wine = load_wine()
#print(data.DESCR)


df=pd.DataFrame(wine["data"][:,0:13],columns=["Alcohol","Malic acid","Ash","Alcalionity","Magnesium","Total Phenol","Flavanoids",
                                             "Nonflavor","Proanthocyanins","Color intensity","Hue","OD280_OD315","Proline"])
'''

		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline])
'''
print(df)
maxi=df.max()
mini=df.min()
print(maxi,mini)
df2=(df-mini)
delta=maxi-mini
df3=df2/delta
df3

     Alcohol  Malic acid   Ash  ...   Hue  OD280_OD315  Proline
0      14.23        1.71  2.43  ...  1.04         3.92   1065.0
1      13.20        1.78  2.14  ...  1.05         3.40   1050.0
2      13.16        2.36  2.67  ...  1.03         3.17   1185.0
3      14.37        1.95  2.50  ...  0.86         3.45   1480.0
4      13.24        2.59  2.87  ...  1.04         2.93    735.0
..       ...         ...   ...  ...   ...          ...      ...
173    13.71        5.65  2.45  ...  0.64         1.74    740.0
174    13.40        3.91  2.48  ...  0.70         1.56    750.0
175    13.27        4.28  2.26  ...  0.59         1.56    835.0
176    13.17        2.59  2.37  ...  0.60         1.62    840.0
177    14.13        4.10  2.74  ...  0.61         1.60    560.0

[178 rows x 13 columns]
Alcohol              14.83
Malic acid            5.80
Ash                   3.23
Alcalionity          30.00
Magnesium           162.00
Total Phenol          3.88
Flavanoids            5.08
Nonflavor             0.66
Proanthocyanins       3.58
Color intensity      13.00
Hue                   1.71
OD280_OD315           4.00
Proline            1680.00
dtype: float64 Alcohol             11.03
Malic acid           0.74
Ash                  1.36
Alcalionity         10.60
Magnesium           70.00
Total Phenol         0.98
Flavanoids           0.34
Nonflavor            0.13
Proanthocyanins      0.41
Color intensity      1.28
Hue                  0.48
OD280_OD315          1.27
Proline            278.00
dtype: float64

      Alcohol  Malic acid       Ash  ...       Hue  OD280_OD315   Proline
0    0.842105    0.191700  0.572193  ...  0.455285     0.970696  0.561341
1    0.571053    0.205534  0.417112  ...  0.463415     0.780220  0.550642
2    0.560526    0.320158  0.700535  ...  0.447154     0.695971  0.646933
3    0.878947    0.239130  0.609626  ...  0.308943     0.798535  0.857347
4    0.581579    0.365613  0.807487  ...  0.455285     0.608059  0.325963
..        ...         ...       ...  ...       ...          ...       ...
173  0.705263    0.970356  0.582888  ...  0.130081     0.172161  0.329529
174  0.623684    0.626482  0.598930  ...  0.178862     0.106227  0.336662
175  0.589474    0.699605  0.481283  ...  0.089431     0.106227  0.397290
176  0.563158    0.365613  0.540107  ...  0.097561     0.128205  0.400856
177  0.815789    0.664032  0.737968  ...  0.105691     0.120879  0.201141

[178 rows x 13 columns]

In [18]:
from sklearn.cluster import KMeans